image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - chmod +x gradlew
  - ps: java -jar ./artifacts/app-card-delivery.jar -P:profile=test &

build_script:
  - ps: ./gradlew test --info "-Dselenide.headless=true"

on_finish:
  - ps: Stop-Process -Id $App.Id

